model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_key: sk-test-key-for-demo-purposes

general_settings:
  master_key: sk-test-123456789
  database_url: sqlite:///./test.db

router_settings:
  routing_strategy: simple-shuffle
