model_list:
  - model_name: test-model
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: test_key_placeholder

general_settings:
  master_key: sk-scalix-dev-123456789
  database_url: sqlite:///./test.db